INTENTOS_MAXIMOS = 3 #NO CAMBIAR ESTO, JODE LA INTERFACE hecha para 3 intentos
PORCENTAJE_A_MOSTRAR = 0.2 #Al 3er intento, te muestro un 60%
CANTIDAD_DE_UNIDADES_DISPONIBLES = 18


RUTA_CSV = "archivo_csv/vocabulario_japones.csv"


ANCHO_VENTANA = 600
ALTO_VENTANA = 600
OPCIONES = ["CLASICO","TIPOS","UNIDAD"]
RUTA_TITULO = "imagenes/titulo.gif"
COLOR_TEXTO_INICIO = "#34495E"


POSICION_OPCCIONES = (60,290)
OPCCIONES_DIMENCION = (150,30)
DIST_OPCIONES = 10
OPCCIONES_COLOR = ["#85C1E9","#E74C3C","#45B39D"]


RESPUESTA_INCORRECTA = "#C0392B"
RESPUESTA_CORRECTA = "#27AE60"

POSICION_MUESTRA_HOR = 300
POSICION_MUESTRA_VER = 100
ENCABEZADO = 35
DISTANCIA_MUESTRA_VER = 100

COLOR_CUADRO_MUESTRA = "#EDBB99" #color Piel
COLOR_HIRAGANA = "#154360" #azul oscuro
COLOR_KATAKANA = "#512E5F" #celeste
COLOR_KANJI = "#78281F" #rojizo

COLOR_PISTA_ENCABEZADO = "#F9E79F" #amarillo claro
COLOR_PISTA = "#FDF2E9" #piel

MENSAJE_PEDIR_NUMERO = ["Ingrese un Numero de PALABRAS o TODO para todas las disponibles","Ingrese un Numero de PALABRAS VALIDO(Mayor a Cero, con Numero y Entero) o TODO para todas las disponibles"]
MENSAJE_PEDIR_UNIDAD = ["Ingrese Una Unidad del みんなの日本語 o TODAS para practica Completa",f"Ingrese Una Unidad del みんなの日本語(disponible desde 1 a {CANTIDAD_DE_UNIDADES_DISPONIBLES} o TODAS para practica Completa"]




RUTA_FIN_JUEGO = "imagenes/game_over.gif"
COLOR_FINAL_FONDO = "#02B5B0" #celeste marino oscuro
COLOR_LETRAS_FINAL = "#FDFEFE" #Blanco

COLOR_SOBRESALIENTE = "#5DADE2" #CELESTE AZUL
COLOR_BIEN = "#58D68D" #VERDE
COLOR_REGULAR = "#F7DC6F" #AMARILLO
COLOR_INSUFICIENTE = "#DC7633" #NARANJA
COLOR_MAL = "#C0392B" #ROJO
COLORES_PUNTUACION = [COLOR_MAL,COLOR_INSUFICIENTE,COLOR_REGULAR,COLOR_BIEN,COLOR_SOBRESALIENTE]

COLOR_CUADRO_PUNTAJE = "#BFC9CA" #Gris

MENSAJE_SOBRESALIENTE = "おめでとう SOBRESALIENTE!!!" 
MENSAJE_BIEN = "とてもいいです　Muy Bien!!! a seguir esforzandose!!!" 
MENSAJE_REGULAR = "だいじょうぶ, OK, falta poco para Aprobar!!!" 
MENSAJE_INSUFICIENTE = "べんきょしましょ a Practicar y Practicar!!!"
MENSAJE_MAL = "べんきょしましょ a Practicar y Practicar!!!" 
MENSAJE_PUNTUACION = [MENSAJE_MAL,MENSAJE_INSUFICIENTE,MENSAJE_REGULAR,MENSAJE_BIEN,MENSAJE_SOBRESALIENTE]